#!/usr/bin/env python3

import logging
import pyudev
import dbus
import struct
import signal
from threading import Timer


"""
struct timeval {
    time_t          tv_sec;
    suseconds_t     tv_usec;
};

struct input_event {
	struct timeval time;
	unsigned short type;
	unsigned short code;
	unsigned int value;
};
"""
event_fmt = '@QQHHI'
event_len = struct.calcsize(event_fmt)
event_unpack = struct.Struct(event_fmt).unpack_from


EV_KEY=1 # when any button is pressed on joystick, inhibit screen saver
EV_ABS=3 # ignore axis moves, since joystick could generate noise even when not touched

TIMEOUT=600


class ScreenSaverHandler:
    cookie = None
    saver = None
    timer = None
    udev = None
    stopped = False
    timeout = TIMEOUT

    def __init__(self):
        iface = 'org.freedesktop.ScreenSaver'
        self.saver = dbus.Interface(dbus.SessionBus().get_object(iface, '/ScreenSaver'), dbus_interface=iface)
        self.udev = pyudev.Context()
        ScreenSaverHandler.instance = self
        signal.signal(signal.SIGINT, sigint)

    def uninhibit(self):
        if not self.cookie:
            return
        self.cookie = self.saver.UnInhibit(self.cookie)
        logging.info('screen saver resumed')

    def inhibit(self):
        self.cookie = self.cookie or self.saver.Inhibit("joysuspend", "joy pressed")
        logging.info(f'screen saver inhibited for {self.timeout} seconds')

        if self.timer:
            self.timer.cancel()
        self.timer = Timer(self.timeout, self.uninhibit)
        self.timer.start()

    def stop(self):
        self.stopped = True
        self.uninhibit()
        if self.timer:
            self.timer.cancel()


def is_button_up(e):
    return e[2] == EV_KEY and e[4] == 0


def device_loop(handler, device):
    with open(device.device_node, 'rb') as f:
        while not handler.stopped:
            data = f.read(event_len)
            if not data: break
            e = event_unpack(data)
            if is_button_up(e):
                handler.inhibit()


def sigint(_signum, _frame):
    ScreenSaverHandler.instance.stop()


def main():
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    handler = ScreenSaverHandler()

    for device in handler.udev.list_devices(subsystem='input', ID_INPUT_JOYSTICK='1'):
        devname = device.device_node
        if devname and devname.startswith('/dev/input/event'):
            logging.debug(device)
            logging.info(f'{device.device_node} {device.parent.properties["NAME"]}')
            device_loop(handler, device)
    logging.info(f'exit')


if __name__ == "__main__":
    main()
